config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-1559
```
[ ] Yes
[x] No
```

suppression of CVEs

---

charts/hmc-hmi-inbound-adapter/Chart.yaml
charts/hmc-hmi-inbound-adapter/values.yaml
src/main/resources/application.yaml

Fix master pipeline

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/CCD-1604
```
[ ] Yes
[X] No
```

CCD-1604 : Fortify Scan implementation for HMI Inbound Adapter

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

use java base chart 3.6.0

---

Jenkinsfile_CNP
build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/InboundAdapterTestAutomationAdapter.java
src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/TestDataLoaderMain.java

https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```

Update to build.gradle

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2593
Suppressing:
CVE-2021-44832, CVE-2021-42550, CVE-2021-43797, CVE-2021-22060, CVE-2022-23181
```
[ ] Yes
[ x] No
```

CCD-2593: Suppress CVE pending investigation

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

Upgrade to Latest Base Helm Charts

---

src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/SwaggerPublisherTest.java
src/main/java/uk/gov/hmcts/reform/hmc/config/SwaggerConfiguration.java

Fix Swagger not picking up any endpoints

---

infrastructure/apim.tf
infrastructure/main.tf
infrastructure/template/api-policy.xml
infrastructure/variables.tf

Initial APIM setup

---

charts/hmc-hmi-inbound-adapter/Chart.yaml
charts/hmc-hmi-inbound-adapter/values.yaml

Add CFT Hearing Service template URL to charts

---

charts/hmc-hmi-inbound-adapter/Chart.yaml
charts/hmc-hmi-inbound-adapter/values.preview.template.yaml
charts/hmc-hmi-inbound-adapter/values.yaml
src/main/resources/application.yaml

Add secrets for S2S/IDAM to charts

---

infrastructure/state.tf

Try state.tf from template

---

charts/hmc-hmi-inbound-adapter/Chart.yaml
charts/hmc-hmi-inbound-adapter/values.preview.template.yaml
charts/hmc-hmi-inbound-adapter/values.yaml

Add system user details to charts

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2925
CVE-2022-21724
```
[ ] Yes
[X ] No
```

Bump Spring Framework to 5.3.18

---

src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/Hearing.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingRoom.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingVenue.java

https://tools.hmcts.net/jira/browse/HMAN-153
```
[ ] Yes
[ ] No
```

Update key names for json payload for PUT /hearing (response)

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerIT.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/Hearing.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingCaseStatus.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingDetailsRequest.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingResponse.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingStatus.java
src/main/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundController.java
src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java

HMAN-145: [PUT Hearing Response] add mandatory validation around field
[HMAN-145] (https://tools.hmcts.net/jira/browse/HMAN-145).

HMAN-145: [PUT Hearing Response] add mandatory validation around field

---

config/owasp/suppressions.xml

--Adding the Suppression for Temporary fix.

---

config/owasp/suppressions.xml

There are dependency check issues with spring-plugin-metadata and spring-plugin-core version, pipeline is failing.This is a suppression change.
```
[ ] Yes
[ x] No
```

Spring-plugin-metadata/core suppression

---

config/owasp/suppressions.xml

There are several dependency check failures, this change is suppressing them.
```
[ ] Yes
[x] No
```

cve multiple issues suppression

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java

https://tools.hmcts.net/jira/browse/CCD-2824
```
[ ] Yes
[X] No
```

jackson.version update for CVE-2020-36518

---

build.gradle
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingCaseStatus.java
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingCode.java
src/main/java/uk/gov/hmcts/reform/hmc/validator/HearingCodeEnumPattern.java
src/main/java/uk/gov/hmcts/reform/hmc/validator/HearingCodeEnumPatternValidator.java
src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
src/test/java/uk/gov/hmcts/reform/hmc/validator/HearingCodeEnumPatternValidatorTest.java

https://tools.hmcts.net/jira/browse/HMAN-174
updated HearingCode enum to support number key value
```
[ ] Yes
[ ] No
```

HMAN-174 update Hearing code enum

---

src/main/resources/application.yaml

HMAN-172 - Ignore unknown properties for deserialisation

---

config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerIT.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
src/main/java/uk/gov/hmcts/reform/hmc/Application.java
src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingService.java
src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImpl.java
src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java

Add latest version validation check - not for Error response……. Add and adjust unit & integration tests
```
[ ] Yes
[X ] No
```

HMAN-144 [PUT Hearing response] Add validation around hearingCaseVersionId

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3187
```
[ ] Yes
[x] No
```

suppression for CVE-2022-24823

---

config/owasp/suppressions.xml

until_date_extension_for_current_CVEs

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingSession.java
src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java

https://tools.hmcts.net/jira/browse/HMAN-256
Fix HearingSession's incorrect mappings
```
[ ] Yes
[x] No
```

HMAN-256 - fix field names for hearingAttendees and hearingJohs

---

build.gradle
src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ServiceException.java
src/main/java/uk/gov/hmcts/reform/hmc/validator/HearingCodeEnumPattern.java
src/main/java/uk/gov/hmcts/reform/hmc/validator/HearingCodeEnumPatternValidator.java
src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/HMAN-254
Increase test coverage for Inbound micro service
```
[ ] Yes
[x] No
```

HMAN-254 - improve code coverage and sonar issues

---

build.gradle

Update azure-messaging-servicebus to latest

---

src/main/resources/application.yaml

Remove non-required scope prior to go live

---

infrastructure/perftest.tfvars

Add custom APIM name suffix for perftest

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-3434
Upgrade Java, postgresql and redis configurations
```
[ ] Yes
[x] No
```

CCD-3434 Upgrade Java, postgresql and redis configurations

---

src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingCode.java
src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java

https://tools.hmcts.net/jira/browse/HMAN-377
```
[ ] Yes
[x] No
```

HMAN-377 - Ignore version check when hearing case status is closed

---

src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/HMAN-371
Need to send rejected response from Future Hearing if listing response has more than one location code.
```
[ ] Yes
[x] No
```

HMAN-371 Check for only 1 EPIMS location.

---

config/owasp/suppressions.xml
infrastructure/apim.tf

Fix OIDC issuer URL for AAT and Prod

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-476
HMAN-476-CVE-2022-41854-Suppression
```
[ ] Yes
[X] No
```

HMAN-476-CVE-2022-41854-Suppression

---

src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfigurationIT.java
src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java

HMAN-443: Monitor failures with the Inbound Adapter
[HMAN-442] (https://tools.hmcts.net/jira/browse/HMAN-443).

 HMAN-443: Monitor failures with the Inbound Adapter

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-250
https://tools.hmcts.net/jira/browse/HMAN-263
https://tools.hmcts.net/jira/browse/HMAN-265
https://tools.hmcts.net/jira/browse/HMAN-416
Fix hmc-hmi-inbound-adapter CVEs  and move false positives (15 total) to false positives section.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

Fix hmc-hmi-inbound-adapter CVEs

---

config/owasp/suppressions.xml

CVE suppression

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-500
CVE-2021-4277 Suppression
```
[ ] Yes
[x ] No
```

HMAN-500 CVE-2021-4277 Suppression

---

.github/workflows/dependency-check.yml
build.gradle
config/owasp/suppressions.xml
gradle/suppress.gradle

https://tools.hmcts.net/jira/browse/HMAN-494
Add suppressCves task
```
[ ] Yes
[ ] No
```

HMAN-494 Add suppressCves task

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-501
Update suppressions.xml
```
[ ] Yes
[X] No
```

HMAN-501: Update suppressions.xml

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-506
Updated Apache Tomcat to 9.0.69 and moved temporary suppressions to false positives section
```
[ ] Yes
[X] No
```

HMAN-506 : Updated Apache Tomcat to 9.0.69 and moved temporary suppressions to false positives

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

https://tools.hmcts.net/jira/browse/HMAN-518
Upgrade base charts
```
[ ] Yes
[X] No
```

HMAN-518 Upgrade base charts

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

NA
Bump Java chart
```
[ ] Yes
[X] No
```

Bump Java chart - Update Chart.yaml

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-530
CVE-2023-20861 for hmc repos
```
[ ] Yes
[ ] No
```

HMAN-530- CVE-2023-20861

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-541
bumped version for jetty and removed suppressions
```
[ ] Yes
[X] No
```

HMAN-541 : bumped version for jetty and removed suppressions

---

build.gradle
charts/hmc-hmi-inbound-adapter/Chart.yaml
charts/hmc-hmi-inbound-adapter/values.preview.template.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-558
HMAN-558 : Fix CVE-2023-2086 (bumped versions of springframework and springsecurity)
```
[ ] Yes
[X] No
```

HMAN-558 : Fix CVE-2023-2086 (bumped versions of springframework and springsecurity)

---

src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerIT.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
src/integrationTest/resources/application-itest.yaml
src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingService.java
src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImpl.java
src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/hmc/ApplicationParamsTest.java
src/test/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/HMAN-573
Terminal State - Ignore List Assist
```
[ ] Yes
[ ] No
```

HMAN-573 : Terminal State - Ignore List Assist

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4949
Fix - Versions below java-logging: 6.0.1
```
[ ] Yes
[ ] No
```

CCD-4949:-CCD-4949

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4771
bumped jackson.version, removed suppression
```
[ ] Yes
[X] No
```

CCD-4771 : Fix CVE-2023-3511

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4994
bumped jetty version to 9.4.53
```
[ ] Yes
[X] No
```

CCD-4994 : Fix-CVE-2023-36478

---

acb.tpl.yaml

https://tools.hmcts.net/jira/browse/HMAN-602
Remove keep:true acb config to fix retry issue
```
[ ] Yes
[ x] No
```

Remove keep:true acb config

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-606
CVE-2023-28709
CVE-2023-41080
CVE-2023-42794
CVE-2023-42795
CVE-2023-45648
CVE-2023-46589
CVE-2023-6378
```
[ ] Yes
[ ] No
```

HMAN-606: CVE-2023 bumps

---

Dockerfile
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4736
Removing https://github.com/advisories/GHSA-xf96-w227-r7c4 suppression and bumping to the next minor version change.
```
[ ] Yes
[x] No
```

Updating suppression and bumping minor version

---

config/owasp/suppressions.xml

[CCD-5024](https://tools.hmcts.net/jira/browse/CCD-5024)
Removed suppression
```
[ ] Yes
[X] No
```

CCD-5024 Update suppressions.xml

---

build.gradle
config/owasp/suppressions.xml

CVE-2023-35116 Fix CVE for HMC repo's
Investigate and fix the vulnerability reported for CVE-2023-35116
```
[ ] Yes
[x] No
```

HMAN-659 Remove CVE-2023-35116 suppression

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-679
fix CVE-2023-44487
```
[ ] Yes
[x] No
```

HMAN-679 fix CVE-2023-44487

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-680
fix CVE-2023-6378
```
[ ] Yes
[x] No
```

HMAN-680 fix CVE-2023-6378

---

charts/hmc-hmi-inbound-adapter/Chart.yaml
charts/hmc-hmi-inbound-adapter/values.yaml

https://tools.hmcts.net/jira/browse/HMAN-668
Upgrade helm chart-chart-java for all CCD Back-end services to version  5.2.0
```
[ ] Yes
[x] No
```

HMAN-668 PI33 Helm chart upgrade - chart-java

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

NA
bump servicebus to 1.0.6 to fix master
```
[ ] Yes
[X] No
```

bump servicebus to 1.0.6 to fix master

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

To allow Azure Service Operator to be upgraded
```
[ ] Yes
[ ] No
```

Chart upgrades

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java

https://tools.hmcts.net/jira/browse/HMAN-873
Hearings not getting created on demo for SSCS
```
[ ] Yes
[ ] No
```

HMAN-873 Update Az service bus jar to latest version

---

config/owasp/suppressions.xml

tidy up on suppressions

---

charts/hmc-hmi-inbound-adapter/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```

CCD-6193 update base chart versions

---

build.gradle

https://tools.hmcts.net/jira/browse/CME-509
```
[ ] Yes
[ ] No
```

CME-509: replace jitpack with azure 
